{
 "title": "Dashboard OEE",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ROUND(\r\n    (\r\n      (SUM(CASE WHEN ligada THEN 1 ELSE 0 END) * 1.0 / NULLIF(COUNT(*), 0)) *\r\n      (SUM(pecas_produzidas) / NULLIF(EXTRACT(EPOCH FROM MAX(datahora) - MIN(datahora)) / 3600, 0)) / 100 *\r\n      (SUM(pecas_produzidas)::float / NULLIF(SUM(pecas_produzidas + pecas_defeituosas), 0))\r\n    )::numeric*100, \r\n    2\r\n  ) AS oee\r\nFROM dados_maquina\r\nWHERE $__timeFilter(datahora)\r\n"
    }
   ]
  },
  {
   "title": "Disponibilidade",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (SUM(CASE WHEN ligada THEN 1 ELSE 0 END) * 1.0 / COUNT(*)) * 100 AS disponibilidade\r\nFROM dados_maquina\r\nWHERE $__timeFilter(datahora)"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (SUM(pecas_produzidas) / (EXTRACT(EPOCH FROM MAX(datahora) - MIN(datahora)) / 3600) / 100) * 100 AS performance\r\nFROM dados_maquina\r\nWHERE $__timeFilter(datahora)\r\n"
    }
   ]
  },
  {
   "title": "Qualidade",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  (SUM(pecas_produzidas)::float / NULLIF(SUM(pecas_produzidas + pecas_defeituosas), 0)) * 100 AS qualidade\r\nFROM dados_maquina\r\nWHERE $__timeFilter(datahora)\r\n"
    }
   ]
  },
  {
   "title": "Total de peças produzidas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(pecas_produzidas) AS total_produzidas\r\nFROM dados_maquina\r\nWHERE $__timeFilter(datahora)\r\n"
    }
   ]
  },
  {
   "title": "Total de peças defeituosas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(pecas_defeituosas) AS total_defeituosas\r\nFROM dados_maquina\r\nWHERE $__timeFilter(datahora)\r\n"
    }
   ]
  }
 ]
}